# AutoMixReg
AutoMixReg provides tools to generate data from and fit mixture of linear regression models using the Expectation-Maximization (EM) algorithm. It includes utilities for model selection via Bayesian Information Criterion (BIC), parameter estimation, simulation, and visualization. The package is useful for clustering in regression settings,....
